name: CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Find solution or project files
        id: findproj
        run: |
          # procura por .sln na raiz e .csproj em subpastas
          SLN_COUNT=$(ls *.sln 2>/dev/null | wc -l || true)
          CSPROJ_COUNT=$(find . -name '*.csproj' | wc -l || true)
          echo "sln_count=$SLN_COUNT" >> $GITHUB_OUTPUT
          echo "csproj_count=$CSPROJ_COUNT" >> $GITHUB_OUTPUT
          echo "Found: $SLN_COUNT .sln files; $CSPROJ_COUNT .csproj files"

      - name: Restore dependencies (if exists)
        if: steps.findproj.outputs.sln_count != '0' || steps.findproj.outputs.csproj_count != '0'
        run: |
          echo "Project/solution found — running dotnet restore"
          dotnet restore Braziliation.sln
      - name: Skip restore (no project found)
        if: steps.findproj.outputs.sln_count == '0' && steps.findproj.outputs.csproj_count == '0'
        run: |
          echo "No .sln or .csproj found — skipping restore/build/test."

      - name: Build (if exists)
        if: steps.findproj.outputs.sln_count != '0' || steps.findproj.outputs.csproj_count != '0'
        run: |
          echo "Building..."
          dotnet build Braziliation.sln --configuration Release --no-restore

      - name: Run tests (if exists)
        if: steps.findproj.outputs.sln_count != '0' || steps.findproj.outputs.csproj_count != '0'
        run: |
          echo "Running tests..."
          dotnet test Braziliation.sln --no-build --verbosity normal

      - name: Post-check
        run: |
          echo "CI job completed. If no .sln/.csproj were found, build/test steps were skipped."
